[package]
name = "skill-utils"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
pathdiff = "0.2.1"
semver = "1.0.23"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
